# .github/workflows/ci.yml

name: OpenFOAM Directory Check
 
on:
  push:
    branches:
      - main

jobs:
  check_directories:
    runs-on: ubuntu-latest
    container: openfoam/openfoam7-paraview56:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for required OpenFOAM directories
      run: |
        icoFoam
